export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREASE_IN_CART = 'INCREASE_IN_CART';
export const DECREASE_FROM_CART = 'DECREASE_FROM_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
